// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dznkqwxdrpzwiqmhgelx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6bmtxd3hkcnB6d2lxbWhnZWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODU2NjcsImV4cCI6MjA2NjI2MTY2N30.OUpqMWRI2nLxfnD70W-3PiAx87cHhepeCZzdZRslWw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);